### ISSUE TITLE
PLEASE ADD README.md

### ISSUE THREAD

**Issue by EricEisaman** [DylanBulmer/TheDocs#1]
Dylan,
  I suggest adding a descriptive readme at the root of this project.  That said, minimalistic design rocks!  What server url should I enter?  I think I'm missing something.
SirFizX

**Comment by DylanBulmer** [comment]
Right now I do not have a public server running, I'm going to develop the server a bit further so when it runs, it will automatically build the database and then I'll upload it to this repo so you can download and run it.

Go to #2 for more information on the database setup

**Comment by EricEisaman** [comment]
Sweet.

**Comment by DylanBulmer** [comment]
A README.md has been created with detailed information about how to setup the server and how to start using the application.
