### ISSUE TITLE
Auto build database on server run

### ISSUE THREAD

**Issue by DylanBulmer** [DylanBulmer/TheDocs#2]
## Problem
The server right now expects a database named `thedocs` to be in place already with all of the tables setup. 

## Solution
I'm going to develop a check system to see if there is a database or schema set up, if there is, then the server will check for the tables, if there is no schema built, the server will build it for you, same goes for the tables.

**Comment by DylanBulmer** [comment]
Referenced from #1

**Comment by EricEisaman** [comment]
Good plan. Have a great weekend!

**Comment by DylanBulmer** [comment]
A new database function `verifyDataBase()` is now called right after the server connects to the database to verify if all of the tables are within the schema and if not they will be created. 

* In the feature, each table will have its own verification function for further analysis of problems lying within a table, thus creating an automatic error-checking system if something fails.
