### ISSUE TITLE
Make server setup easier

### ISSUE THREAD

**Issue by DylanBulmer** [DylanBulmer/TheDocs#3]
**Problem:**
The server has a lot of steps to set it up and the start up is not well built. 

**Solution:**
Use https://github.com/nexe/nexe to make the server an executable and create a "first time setup" command line interface.

**Comment by DylanBulmer** [comment]
Switching to https://npmjs.com/pkg due to nexe not being able to support some of the modules in my application.

This server will be moved to it's own project for further development once the executable is done. 

The admin page will be done soon. I am thinking about adding the admin page into the application by calling it in a iFrame so only "admin" users can get to it.

**Comment by EricEisaman** [comment]
Consider using admin property on your administrative users.  Employ a conditional redirect at the route endpoint for unqualified visitors.
[Illustrated in Video](https://www.safaribooksonline.com/library/view/nodejs-web-apps/9781491958940/video242314.html)
[Reasons not to use iFrames](https://www.ostraining.com/blog/webdesign/against-using-iframes/)

**Comment by DylanBulmer** [comment]
@EricEisaman I have done a little bit of research with security with Electron and Node JS because I do want users to be able to click on links with in the app for convenience. Through my research I found the following link that has many warning about security to keep in mind while developing, and more specifically how to _"Disable Node.js Integration for Remote Content"_

https://electronjs.org/docs/tutorial/security#2-disable-nodejs-integration-for-remote-content

Within the URL provided I found that there is a "webview" tag that ElectronJS built that will stop external sites from attacking Node code and the users computer.

https://electronjs.org/docs/api/webview-tag

Example:
`<webview src="http://www.google.com/"></webview>`

**Comment by DylanBulmer** [comment]
The Server is now located @ https://github.com/DylanBulmer/TheDocs-Server

All new issues will be processed in it's own repository.

**Comment by DylanBulmer** [comment]
Closing issue, server is in different repository and is being rebuilt soon.
