### ISSUE TITLE
Auto Updater stopped working

### ISSUE THREAD

**Issue by DylanBulmer** [DylanBulmer/TheDocs#5]
## Problem:
The auto-updater stopped working, investigation will start soon.

**Comment by EricEisaman** [comment]
Have you considered [hazel](https://github.com/zeit/hazel)?

**Comment by DylanBulmer** [comment]
The problem isn't how it is deployed, but more of the code to find and download the latest version on the application. The auto-updater was working between versions 0.1.0 and 0.1.1, I haven't looked into my code, but I think I either moved a few lines or maybe removed a few too many during the 0.1.2 release. 

I know that the app will not be able to auto-update on Mac OS until I sign the application with a certification, but it should still work on Windows, my latest release did not go through without a manual installment.

**Comment by DylanBulmer** [comment]
I think this might be an "ownership" issue, as in that if TheDocs was installed a user and you switch to another user, that other user cannot update TheDocs. 

On my computer, I have my personal user "Dylan", and I have my "Programming" user. I initially installed TheDocs on "Programming" which stopped me from updating on "Dylan," but when I went back over and opened up TheDocs, I was prompted to restart and install.
